### PR TITLE
adding new tld's

### PR DESCRIPTION
**Pull request by maarten-boot**
I am using your code for a project where we gather ransomware related domains and as a result i am adding more tld's to your list.

Also i added a formatter to enforce code formatting and added a bit of extra white-space and some explanations/hints (e.g the recursive call to flatten the regexes)

If you are interested you can merge, i will be evaluating more tld's in the next few weeks and make a new update after that.

### CODE REVIEW

**Comment by mimi89999** [comment]
Why did you add the `out` and `2` files?

**Comment by maarten-boot** [comment]
that is my error it is the test output of python3 ./test.py 2>2 | tee out
i will add them to gitignore on the next pull request
currently adding server support whois -h server (needed for example
.monster toplevel domain)

**Comment by mimi89999** [comment]
Also, wouldn't it be better to add the linter as a CI task than a raw script?

**Comment by maarten-boot** [comment]
naturally but i dont have a CI environment ;-)
but i can remove the script

**Pull request merged**
