### PR TITLE
Added .az, .es and gov.tr TLD support & fix Turkish character

### PR DESCRIPTION
**Pull request by kaloomte**
I added .az, .es and gov.tr TLD support also i fix broken Turkish utf-8 character with added server which has utf-8 support.

### CODE REVIEW

**Comment by maarten-boot** [comment]
the tld's for es  redirects directly to whois.nic.es and gives no data for my test domains meta and google
whois meta.es -h whois.iana.org
[Querying whois.iana.org]
[Redirected to whois.nic.es]
[Querying whois.nic.es]
[whois.nic.es]
and as seen from: https://www.iana.org/domains/root/db/es.html the official whois server for tld es is whois.nic.es

as seen in the iana db there is no whois server for az currently

https://www.iana.org/domains/root/db/az.html
the do support web queries but we dont

i will add the gov.tr and the utf-8

**Comment by maarten-boot** [comment]
i see the gov.tr and the fis for name-servers having trailing data on the line but i fail to see the utf-8 fix
i have added the gov.tr to the https://github.com/mboot-github/WhoisDomain
and will sync the code later from there to this repo

what example output do you have for "az" and "es"

**Comment by maarten-boot** [comment]
the gov.tr has been added

**Comment by kaloomte** [comment]
> i see the gov.tr and the fix for name-servers having trailing data on the line but i fail to see the utf-8 fix i have added the gov.tr to the https://github.com/mboot-github/WhoisDomain and will sync the code later from there to this repo
> 
> what example output do you have for "az" and "es"

**Comment by kaloomte** [comment]
Your are right about .az and .es my mistake but for non broken Turkish character i set the _server : whois.trabis.gov.tr.

**Comment by maarten-boot** [comment]
no problem , you can see in https://github.com/DannyCork/python-whois/blob/master/whois/tld_regexpr.py#L290
i grouped all sub levels and tld: tr together , all now use the new official whois server for tld: tr
thanks for the update

**Comment by maarten-boot** [comment]
note taht _server hints currently do not get ingerited when using extend, i realise that may actually be my error in the implementation, so if you want the other second level domains ot "tr" also to use the new whois server we will have to set that explicitly per tld currently

**Comment by maarten-boot** [comment]
i added the explicit  serverhints in:
https://github.com/mboot-github/WhoisDomain/blob/master/whoisdomain/tld_regexpr.py#L307
and will sync the code soon

**Pull request closed without merging**
