### PR TITLE
Add support for new Top Level Domains

### PR DESCRIPTION
**Pull request by windgmbh**
I am currently adding support for a few more Top Level Domains.

### CODE REVIEW

**Comment by windgmbh** [comment]
Test Output: 

```
google.kn
                name	"google.kn"
                 tld	"kn"
           registrar	"MarkMonitor Inc."
  registrant_country	"US"
       creation_date	"2011-04-04 04:00:00"
     expiration_date	"2023-04-04 04:00:00"
        last_updated	"2022-03-23 17:45:01.599000"
              status	"clientRenewProhibited https://icann.org/epp#clientRenewProhibited"
            statuses	"['clientRenewProhibited https://icann.org/epp#clientRenewProhibited', 'clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited', 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited']"
              dnssec	"False"
        name_servers	"['ns1.google.com', 'ns2.google.com', 'ns3.google.com', 'ns4.google.com']"
          registrant	"Google LLC"

google.kg
                name	"at http://www.cctld.kg"
                 tld	"kg"
           registrar	"Markmonitor"
  registrant_country	""
       creation_date	"2004-02-10 09:42:42"
     expiration_date	"2023-03-29 23:59:00"
        last_updated	"2018-12-20 05:38:37"
              status	""
            statuses	"['']"
              dnssec	"False"
        name_servers	"[]"

google.fo
                name	"google.fo"
                 tld	"fo"
           registrar	"FO Umsitingin"
  registrant_country	""
       creation_date	"2011-07-22 22:38:12"
     expiration_date	"2023-07-22 23:59:59"
        last_updated	"2022-10-03 10:40:48"
              status	"ok https://icann.org/epp#ok"
            statuses	"['ok https://icann.org/epp#ok']"
              dnssec	"False"
        name_servers	"['ns1.markmonitor.com', 'ns3.markmonitor.com']"
          registrant	""

google.tokyo
                name	"google.tokyo"
                 tld	"tokyo"
           registrar	"MarkMonitor Inc."
  registrant_country	"US"
       creation_date	"2014-06-07 07:54:00"
     expiration_date	"2022-12-04 23:59:59"
        last_updated	"2021-12-01 22:35:57"
              status	"clientTransferProhibited https://icann.org/epp#clientTransferProhibited"
            statuses	"['inactive https://icann.org/epp#inactive', 'clientTransferProhibited https://icann.org/epp#clientTransferProhibited', 'clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited', 'clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited']"
              dnssec	"False"
        name_servers	"[]"
          registrant	""
```

**Comment by windgmbh** [comment]
@DannyCork 
I am currently writing some scripts where I need to analyze a larger dataset of mainly ccTLD and noticed that some of them were still unsupported. 

I have created this pull request for adding any domains that I will have to implement in the process.

At this point I just wanted to ask whether I have done these four TLDs properly in order to avoid making the same mistake many times, potentially.

**Comment by maarten-boot** [comment]
looks all good as far as i can see

**Comment by baigreen** [comment]
Great work

**Comment by maarten-boot** [comment]
this looks all good to me, i suggest to merge the request if no conflicts

**Pull request merged**
