### PR TITLE
For pl registry, if 'option expiration date' is not present, 'renewaldate' should be treated as the expiry date

### PR DESCRIPTION
**Pull request by kazet**

### CODE REVIEW

**Comment by kazet** [comment]
Hello,

for example:

option expiration date present: wp.pl or onet.pl (major Polish information
sites),
no option, only renewal date: google.pl

Best,
Krzysztof Zając

**Comment by maarten-boot** [comment]
actually wp.pl has both:

```
whois wp.pl
[Querying whois.dns.pl]
[whois.dns.pl]

DOMAIN NAME:           wp.pl
registrant type:       organization
nameservers:           ns1.task.gda.pl. [153.19.250.101]
                       ns1.wp.pl. [212.77.106.200]
                       ns2.wp.pl. [153.19.88.162]
created:               1998.04.28 13:00:00
last modified:         2023.03.16 14:06:06
renewal date:          2024.04.27 14:00:00

option created:        2020.02.10 10:51:12
option expiration date:       2026.02.10 10:51:12

dnssec:                Unsigned


REGISTRAR:
AZ.pl Sp. z o.o.
ul. Zbożowa 4
70-653 Szczecin
Polska/Poland
+48.914243780
domena@az.pl

WHOIS database responses: https://dns.pl/en/whois

WHOIS displays data with a delay not exceeding 15 minutes in relation to the .pl Registry system
```

and onet.pl also has both:

```
whois onet.pl
[Querying whois.dns.pl]
[whois.dns.pl]

DOMAIN NAME:           onet.pl
registrant type:       organization
nameservers:           ns5.ringpublishing.net. 
                       ns6.ringpublishing.net. 
                       ns7.ringpublishing.net. 
                       ns8.ringpublishing.net. 
created:               1996.06.22 01:00:00
last modified:         2022.12.21 00:30:20
renewal date:          2023.12.31 13:00:00

option created:        2019.08.20 19:44:39
option expiration date:       2025.08.20 19:44:39

dnssec:                Unsigned


REGISTRAR:
cyber_Folks S.A.
ul. Franklina Roosevelta 22
60-829 Poznań
Polska/Poland
tel.: +48.122963663
info@domeny.pl

WHOIS database responses: https://dns.pl/en/whois

WHOIS displays data with a delay not exceeding 15 minutes in relation to the .pl Registry system
```

meaning your rule would not apply, is there a example without a expiration date present ?
where renewal date would actually be used ?

**Comment by maarten-boot** [comment]
also note that renewal date is frequently behind the expire date

**Comment by maarten-boot** [comment]
sorry for deleting the 2 comments i made earlier, i logged in as the wrong user , my bad

**Comment by maarten-boot** [comment]
yes confirmed with google.pl 
all ok

**Comment by maarten-boot** [comment]
the pip whoisdomain package has been updated to include your patch (whoisdomain 1.20231102.1 )

https://pypi.org/project/whoisdomain/

**Pull request merged**
